//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmcsST10024703.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContractMonthlyClaimsST10024703Entities : DbContext
    {
        public ContractMonthlyClaimsST10024703Entities()
            : base("name=ContractMonthlyClaimsST10024703Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Claim> Claims { get; set; }

        public System.Data.Entity.DbSet<cmcsST10024703.Models.User> Users { get; set; }
    }
}
